### PR TITLE
Add hyperbolic functions to standard environment

### PR DESCRIPTION
**Pull request by resurrexit**
Added the six hyperbolic functions listed in #25 to the standard environment, along with accompanying unit tests.

### CODE REVIEW

**Comment by jakerockland** [comment]
Awesome @resurrexit -- seems like the unit tests are not currently passing though, have you gotten a chance to look at this? https://travis-ci.org/jakerockland/Swisp/builds/285896002

**Comment by jakerockland** [comment]
Unfortunately don't have the time right now to look into this myself.

**Comment by resurrexit** [comment]
Will look at it now.

**Comment by resurrexit** [comment]
I know why it failed: I have the newest version of XCode, where XCTAssertEqualWithAccuracy was deprecated. I was using XCTAssertEqual instead.

Tried installing the older toolchain to match the version of Swift we have here, and compilation was failing. I was trying to ignore the fact that I couldn't get the older toolchain to work! 🙈🙈🙈

Will get that working for future PR's.

**Comment by resurrexit** [comment]
Code coverage is reduced because there are no situations in which unit testing will hit the default block for the switch statement for asinh, cosh, sinh, and tanh. If you look at the graphs for those four functions, the domains for those four functions are (-∞, +∞).

Also, note that currently we do not have integer support for the trig functions OR the hyperbolic functions.
screen shot 2017-10-10 at 01 11 26

As R5RS states:
screen shot 2017-10-10 at 17 24 04

I was going to open an issue on this and fix this 😅

**Comment by jakerockland** [comment]
@resurrexit Great work, this looks good to me. Upgrading this project to Swift 4 and to work with the latest build tools is something I've been meaning to do but haven't had time for lately--sorry for the headache.

Adding the integer support you mentioned is a great idea, would very much appreciate you opening an issue and fixing! 😄

**Pull request merged**
